name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Використовуйте відповідну версію JDK

      - name: Compile Java files
        run: |
          javac -d bin src/**/*.java  # Компіляція ваших Java файлів (переконайтеся, що ваші файли знаходяться в директорії src)

      - name: Run Tests
        run: |
          java -cp bin org.junit.runner.JUnitCore CalculatorTest  # Приклад тестування з JUnit. Замініть на ваш клас тестів
          
  deploy:
    name: Simulate Deployment
    runs-on: ubuntu-latest
    needs: test  # Потрібно, щоб крок "test" завершився успішно

    steps:
      - name: Simulate Deployment
        run: echo "Deployed"
