name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка JDK 11 (Adoptium/Temurin)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Шаг 3: Компиляция и запуск тестов вручную (если нет сборщика)
      - name: Compile and Run tests
        run: |
          javac -cp .:$(find . -name '*.jar' | tr '\n' ':') -d bin $(find . -name '*.java')
          java -cp bin org.junit.platform.console.ConsoleLauncher --scan-classpath
