name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile Java code
        run: |
          javac Calculator.java

      - name: Run tests
        run: |
          java org.junit.runner.JUnitCore CalculatorTest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Deploy (simulated)
        run: echo "Deployed"
