name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Compile Java files
        run: |
          javac -d bin src/**/*.java  # Компіляція ваших Java файлів

      - name: Set environment variable
        run: echo "DISTRIBUTION=some_value" >> $GITHUB_ENV  # Передача змінної середовища

      - name: Run Tests with parameters
        run: |
          java -cp bin org.junit.runner.JUnitCore CalculatorTest --distribution $DISTRIBUTION
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}  # Передача змінної середовища зі сховища секретів або через GitHub Actions

  deploy:
    name: Simulate Deployment
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Simulate Deployment
        run: echo "Deployed"
