name: Java CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Крок 1: Клонування репозиторію
    - name: Checkout code
      uses: actions/checkout@v3

    # Крок 2: Налаштування JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Крок 3: Компиляція та запуск тестів
    - name: Compile and Test
      run: |
        javac Calculator.java # Скомпілювати Java-файл
        java Calculator # Запустити програму

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Крок 4: Симуляція деплою
    - name: Simulate Deployment
      run: echo "Deployed"
